name: Template
on:
  push:
    branches:
      - main

jobs:

  template-cleanup:
    name: Template
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'tauri-template'
    steps:

      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Template
        shell: bash
        run: |
          set -ex
          shopt -s dotglob nullglob

          # Prepare variables
          NAME="${GITHUB_REPOSITORY##*/}"
          ACTOR=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')
          SAFE_NAME=$(echo $NAME | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          SAFE_ACTOR=$(echo $ACTOR | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          GROUP="com.github.$SAFE_ACTOR.$SAFE_NAME"

          npm install -g @vue/cli
          cargo install tauri-bundler

          vue create --default --packageManager npm --no-git "$SAFE_NAME"
          mv "$SAFE_NAME"/* ./
          mv "$SAFE_NAME"/.gitignore .gitignore
          rm -r "$SAFE_NAME"/
          git add -A
          git commit -m "Generate vue tauri app"

          vue add tauri --ci
          git add -A
          git commit -m "Added vue tauri"

          # Replace workflows
          rm -rf .github/workflows
          mv .github/template_workflows .github/workflows
          git add -A
          git commit -m "Set up workdlow"
      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
