name: Template
on:
  push:
    branches:
      - main

jobs:

  template-cleanup:
    name: Template
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'tauri-template'
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Template
        shell: bash
        run: |
          set -ex
          shopt -s dotglob nullglob

          # Prepare variables
          NAME="${GITHUB_REPOSITORY##*/}"
          ACTOR=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')
          SAFE_NAME=$(echo $NAME | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          SAFE_ACTOR=$(echo $ACTOR | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          GROUP="com.github.$SAFE_ACTOR.$SAFE_NAME"

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          npm install -g @vue/cli
          cargo install tauri-bundler

          vue create --default --packageManager yarn --no-git "$SAFE_NAME"
          mv "$SAFE_NAME"/* ./
          rm -r "$SAFE_NAME"
          git add -A
          git commit -m "Generate vue app"

          vue add tauri --ci
          cargo fmt --verbose --manifest-path src-tauri/Cargo.toml
          git add -A
          git commit -m "Added vue tauri"

          # Remove template workflow
          rm -f .github/workflows/template.yml
          sed -i "s|tauri-template|$SAFE_NAME|g" README.md

          git add -A
          git commit -m "Remove template workflow"
      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -fv \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -u "$GITHUB_ACTOR:$GITHUB_TOKEN" \
            -d '{"ref":"refs/heads/main"}' \
            "https://api.github.com/repos/$GITHUB_ACTOR/$GITHUB_REPOSITORY/actions/workflows/build.yml/dispatches"
